baseurl: "https://resampledbrain.netlify.app/"
publishDir: "docs"
languageCode: en-us
title: The Resampled Brain
sidebarFreeText: ""
theme: "strange-case-2"
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: https://resampledbrain.netlify.app/about
    - name: GitHub
      url: https://github.com/ddixonAI
    - name: Twitter
      url: https://twitter.com/ddixonAI
    - name: LinkedIn
      url: https://www.linkedin.com/in/derek-dixon-50870019b/
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: 
  sidebarFreeText: Musings plucked at random without replacement from beyond the foamy sponge of my brain
  colorScheme: "scheme-darkbrown"
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
